wharfie:
    image: qnib/go-wharfie:latest
    net: host
    environment:
      DOCKER_HOST: ${DOCKER_HOST}
      DOCKER_CERT_PATH: ${DOCKER_CERT_PATH}
    volumes:
      - ${HOME}:${HOME}:ro
      - /var/run/docker.sock:/var/run/docker.sock
